repository: athackst/jekyll-theme-profile
style: topbar # One of "stacked", "sidebar", "topbar"
user_image: /assets/img/user-image.jpg
social_image: /screenshot.png
# icon_color: "#959da5"
# background:
#   image: /assets/img/background-img.jpg
#   light:
#     overlay: rgba(255, 255, 255, 0.5)
#   dark:
#     overlay: rgba(0, 0, 0, 0.5)

plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      breadcrumbs: true
      permalink: /blog/:year/:month/:day/:title.html

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - .vscode
  - .devcontainer
  - .deprecated
  - .github
  - "*.gem"

paginate: 6
paginate_path: "/assets/blog/page:num"

markdown: kramdown

posts_limit: 3

nav:
  - name: Topbar
    url: /test/home/topbar.html
  - name: Sidebar
    url: /test/home/sidebar.html
  - name: Stacked
    url: /test/home/stacked.html

links:
  - name: Example page with topbar
    url: /test/page/topbar
    thumbnail: /assets/img/icon-topbar.png
  - name: Example page with sidebar
    url: /test/page/sidebar
    thumbnail: /assets/img/icon-sidebar.png
  - name: Example page with header stacked
    url: /test/page/stacked
    thumbnail: /assets/img/icon-stacked.png
  - name: Example page with a custom background
    url: /test/page/background
    thumbnail: /assets/img/icon-bg.png

repositories:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      # - respositories to exclude

social_media:
  # behance: your_username
  # dribbble: your_username
  # docker: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # threads: your_username
  # tiktok: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # vscode: your_username
  # youtube: your_username
  # x: your_username
