repository: athackst/jekyll-theme-profile
style: topbar # One of "stacked", "sidebar", "topbar"
user_image: /assets/img/user-image.jpg
image: /screenshot.png

plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

defaults:
  - scope:
      type: pages
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      breadcrumbs: true
      permalink: /blog/:year/:month/:day/:title.html

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - .vscode
  - .devcontainer
  - .deprecated
  - .github
  - "*.gem"

paginate: 6
paginate_path: "/assets/blog/page:num"

markdown: kramdown

posts_limit: 3

links:
  - name: Example page with topbar
    web_url: /test/page/topbar
    image_url: /assets/img/icon-topbar.png
  - name: Example page with sidebar/
    web_url: /test/page/sidebar
    image_url: /assets/img/icon-sidebar.png
  - name: Example page with header stacked
    web_url: /test/page/stacked
    image_url: /assets/img/icon-stacked.png

repositories:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      # - respositories to exclude
