repository: athackst/jekyll-theme-profile
# The style of the website
style: topbar # One of "stacked", "sidebar", "topbar"
 # The user/project avatar.  If not set the avatar of the project owner will be used.
user_image: /media/user-image.jpg
# Optional custom background image and overlay
# background:
#   image: /media/background-img.jpg
#   light:
#     overlay: rgba(255, 255, 255, 0.5)
#   dark:
#     overlay: rgba(0, 0, 0, 0.5)

repo_info: true # Show the information for the source of this project
metadata: false # Show the metadata associated with the user

####################
# Social media
social_image: /screenshot.png # The social media thumbnail image to use in post links.
# icon_color: "#959da5" # The color of the social media icons on the site
social_media: # Your social media accounts
  # behance: your_username
  # dribbble: your_username
  # docker: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # threads: your_username
  # tiktok: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # vscode: your_username
  # youtube: your_username
  # x: your_username

####################
# Navigation links
nav:
  - name: Topbar
    url: /test/home/topbar.html
  - name: Sidebar
    url: /test/home/sidebar.html
  - name: Stacked
    url: /test/home/stacked.html

####################
# List of links for home page
links:
  - name: Example page with topbar
    url: /test/page/topbar
    thumbnail: /media/icon-topbar.png
  - name: Example page with sidebar
    url: /test/page/sidebar
    thumbnail: /media/icon-sidebar.png
  - name: Example page with header stacked
    url: /test/page/stacked
    thumbnail: /media/icon-stacked.png
  - name: Example page with a custom background
    url: /test/page/background
    thumbnail: /media/icon-bg.png

###################
# Repositories to show on home page
repositories:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      # - list of respositories to exclude

####################
# Blog
posts_limit: 3 # The number of posts to show in home

paginate: 6 # The number of posts to show per page of pagination of blog posts
paginate_path: "/assets/blog/page:num"

# ============= general settings for the theme ===============
plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      breadcrumbs: true
      permalink: /blog/:year/:month/:day/:title.html

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - .vscode
  - .devcontainer
  - .deprecated
  - .github
  - "*.gem"

markdown: kramdown
