repository: athackst/jekyll-theme-profile
# The style of the website
style: topbar # One of "stacked", "sidebar", "topbar"
 # The user/project avatar.  If not set the avatar of the project owner will be used.
user_image: /media/user-image.jpg
# Optional custom background image and overlay
# background:
#   image: /media/background-img.jpg
#   overlay: rgba(0, 0, 0, 0.7)
#   light:
#     overlay: rgba(255, 255, 255, 0.5)
#   dark:
#     overlay: rgba(0, 0, 0, 0.5)

# Optional custom header colors
# header:
#   color: "#4051b5"
#   text: "rgba(255,255,255,0.7)"
#   accent: "#ffffff"

repo_info: true # Show the information for the source of this project
metadata: true # Show the metadata associated with the user
profile_link: true # Show a link to the github profile for the user

####################
# Social media
social_image: /screenshot.png # The social media thumbnail image to use in post links.
# icon_color: "#959da5" # The color of the social media icons on the site
# social_media: # Your social media accounts
#   behance: your_username
#   dribbble: your_username
#   docker: your_username
#   facebook: your_username
#   github: your_username
#   hackerrank: your_username
#   instagram: your_username
#   keybase: your_username
#   linkedin: your_username
#   mail: email@address
#   mastodon: your_username
#   medium: your_username
#   stackoverflow: your_user_id
#   telegram: your_username
#   threads: your_username
#   tiktok: your_username
#   twitter: your_username
#   unsplash: your_username
#   vk: your_username
#   vscode: your_username
#   youtube: your_username
#   x: your_username

####################
# Navigation links
nav:
  - name: Topbar
    url: /test/home/topbar.html
  - name: Appbar
    url: /test/home/appbar.html
  - name: Sidebar
    url: /test/home/sidebar.html
  - name: Stacked
    url: /test/home/stacked.html

####################
# List of links for home page
links:
  - name: Example page with topbar
    url: /test/page/topbar
    thumbnail: /media/topbar-icon.png
  - name: Example page with appbar
    url: /test/page/appbar
    thumbnail: /media/appbar-icon.png
  - name: Example page with sidebar
    url: /test/page/sidebar
    thumbnail: /media/sidebar-icon.png
  - name: Example page with header stacked
    url: /test/page/stacked
    thumbnail: /media/stacked-icon.png
  - name: Example page with a custom background
    url: /test/page/background
    thumbnail: /media/icon-bg.png
  - name: Example Linktree page
    url: /test/linktree
    thumbnail: /media/links.png

###################
# Repositories to show on home page
repositories:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      # - list of respositories to exclude

####################
# Blog
posts_limit: 3 # The number of posts to show in home

paginate: 6 # The number of posts to show per page of pagination of blog posts
paginate_path: "/assets/blog/page:num"

markdown: kramdown
highlighter: rouge
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
#   syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
#     css_class: highlight
#     # default_lang: console
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1

# ============= general settings for the theme ===============
plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      breadcrumbs: true
      permalink: /blog/:year/:month/:day/:title.html
      toc: true

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - .vscode
  - .devcontainer
  - .deprecated
  - .github
  - "*.gem"
