# ######## Jekyll Site Settings ##########
theme: jekyll-theme-profile
title: Jekyll Theme Profile
description: Theme built with jekyll-theme-profile
image: /assets/img/social-preview.png
repository: "PrimerPages/jekyll-theme-profile"

collections:
  docs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      image: /assets/img/default.png # The default image used for social and posts.
      toc: true
  - scope:
      path: "" # an empty string here means all files in the project
      type: "docs"
    values:
      layout: "docs"
      image: /assets/img/default.png # The default image used for social and posts.
      index: /docs/index.html
      permalink: /docs/:path:output_ext
      edit_url: "https://github.com/PrimerPages/jekyll-theme-profile/edit/main/demo"
      toc: true

# ########### Theme settings ###############
# The style of the website
style: appbar # One of "stacked", "sidebar", "topbar", "appbar"
# The user/project avatar.  If not set the avatar of the project owner will be used.
user_image: /assets/img/user-image.jpg
# The site logo/favicon
favicon: /media/appbar-icon.png
# The themes to use for dark and light
dark_theme: dark_dimmed
light_theme: light
# # Optional custom background image and overlay
# background:
#   image: /media/background-img.jpg
#   overlay: rgba(0, 0, 0, 0.7)
#   light:
#     overlay: rgba(255, 255, 255, 0.5)
#   dark:
#     overlay: rgba(0, 0, 0, 0.5)

# # Optional custom header colors
# header:
#   color: "#4051b5"
#   text: "rgba(255,255,255,0.7)"
#   accent: "#ffffff"

repo_info: true # Show the information for the source of this project
user_metadata: true # Show the metadata associated with the user
profile_link: true # Show a link to the github profile for the user

##########################
# # Social media settings
icon_color: "#959da5" # The color of the social media icons on the site
social_media: # Your social media accounts
  # behance: your_username
  # dribbble: your_username
  # docker: your_username
  # facebook: your_username
  github: athackst
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mail: email@address
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # threads: your_username
  # tiktok: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  vscode: althack
  # youtube: your_username
  x: althack

####################
# Navigation links
nav:
  - name: Appbar
    url: /appbar.html
  - name: Sidebar
    url: /sidebar.html
  - name: Stacked
    url: /stacked.html
  - name: Topbar
    url: /topbar.html
  - name: Documentation
    url: /docs

####################
# List of links for link cards
links:
  - name: Example Linktree page
    url: /linktree
    octicon: link
  - name: Example Profile page
    url: /profile
    octicon: person
  - name: Example Repositories page
    url: /repositories
    octicon: repo
  - name: Example landing page
    url: /landing
    octicon: rocket
  - name: Example blog index
    url: /blog
    octicon: comment
  - name: Example category index
    url: /category
    octicon: stack
  - name: Example tag index
    url: /tags
    octicon: tag
  - name: Custom background
    url: /custom-background
    octicon: device-desktop
  - name: Custom header
    url: /custom-header
    octicon: browser

###################
# Repositories to show on home page
repositories:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      # - list of repositories to exclude

########################
# Post settings
related_by: "tags or categories"

# ########### Plugin settings ###############
plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji
  - jekyll-meta
####################
# jekyll-paginate settings
paginate: 7 # The number of posts to show per page of pagination of blog posts
paginate_path: "/blog/page:num"
###################
# jekyll-tagging settings
# Include `gem jekyll-tagging` in your gemfile
tag_page_layout: tags
tag_page_dir: tags
####################
# jekyll-category-pages settings
category_path: category
category_layout: category_layout.html
######################
# jekyll-relative-links settings
relative_links:
  enabled:     true
  collections: true
