# frozen_string_literal: true

source 'https://rubygems.org'
gem "jekyll-theme-profile", :path => "../"

group :jekyll_plugins do
  gem 'jekyll-category-pages' # Recommended for category index
  gem 'jekyll-paginate' # Recommended for blog index
  gem 'jekyll-relative-links' # Needed to create relative links
  gem 'jekyll-sitemap' # Needed to create a sitemap
  gem 'jekyll-tagging' # Recommended for tagging index
  gem 'jekyll-github-metadata', '= 2.13.0' # Needed to rate limit calls
  gem 'jekyll-octicons' # Needed for octicons
  gem 'jekyll-meta' # Needed for scss version
  gem 'jekyll-toc' # Needed for table of contents in posts
end

group :development do
  gem 'dotenv', '~> 2.7'
  gem 'html-proofer'
end
