name: Draft release

on:
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write # for release-drafter/release-drafter and Bump version
      pull-requests: write # for release-drafter/release-drafter and Bump version
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout main branch
        uses: actions/checkout@v4

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Get release draft
        uses: release-drafter/release-drafter@v6.1.0
        id: release-draft
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Get version and changelog info
      - name: Get version and changelog info
        run: |
          VERSION=${{ steps.release-draft.outputs.tag_name }}
          VERSION=${VERSION#v} # Strip leading 'v' if present
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "${{ steps.release-draft.outputs.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Update version
      - name: Update version
        run: |
          echo "$VERSION" > VERSION

      # Create a release PR
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: release/v${{ env.VERSION }}
          title: "Release v${{ env.VERSION }}"
          body: |
            Release version ${{ env.VERSION }}

            ${{ env.CHANGELOG }}
          commit-message: "Bump version to v${{ env.VERSION }}"
          delete-branch: true
