name: Draft release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write # for release-drafter/release-drafter and Bump version
      pull-requests: write # for release-drafter/release-drafter and Bump version
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release-draft.outputs.tag_name }}
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6.1.0
        id: release-draft
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
