name: Release gem

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.243.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems
      - name: Determine release version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "GEM_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "GEM_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Check release version matches
        run: |
          VERSION=$(cat VERSION)
          if [ "$VERSION" != "$GEM_VERSION" ]; then
            echo "Version from file: $VERSION"
            echo "Version from release: $GEM_VERSION"
            echo "Versions do not match!"
            exit 1
          fi
      - name: Release
        run: .github/release.sh jekyll-theme-profile.gemspec
        env:
          RUBYGEMS_USERNAME: ${{ secrets.RUBYGEMS_USERNAME }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
