name: Draft release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write # for release-drafter/release-drafter and Bump version
      pull-requests: write # for release-drafter/release-drafter and Bump version
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release-draft.outputs.tag_name }}
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5.25.0
        id: release-draft
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4

  bump_version:
    runs-on: ubuntu-latest
    needs: update_release_draft
    steps:
      - uses: actions/checkout@v4
      - name: Bump version
        env:
          VERSION: ${{ needs.update_release_draft.outputs.tag_name }}
        run: |
          echo "Bumping version to ${VERSION}"
          .github/bump.sh jekyll-theme-profile.gemspec ${VERSION}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version to ${{ needs.update_release_draft.outputs.tag_name }}
          title: Bump version to ${{ needs.update_release_draft.outputs.tag_name }}
          body: |
            Bump version to ${{ needs.update_release_draft.outputs.tag_name }}
          branch: skip/version-bump-${{ needs.update_release_draft.outputs.tag_name }}
          labels: |
            version-bump
            skip-changelog
      - name: Merge pull request
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Merging pull request"
          gh pr merge --auto --rebase --delete-branch "${{ steps.cpr.outputs.pull-request-number }}"
