name: Draft release PR

on:
  push:
    branches:
      - main  # Updates the PR only if it already exists
  workflow_dispatch:  # Manually trigger to create a new PR

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for updating release notes
      pull-requests: write  # Required for modifying the PR
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Run Release Drafter
        id: release-draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        run: |
          echo "${{ steps.release-draft.outputs.tag_name }}" > VERSION

      - name: Close old Release PR if the version changed
        run: |
          .github/close_stale.sh
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Release PR
        uses: peter-evans/create-pull-request@v5
        if: github.event_name == 'workflow_dispatch' || env.PR_EXISTS == 'true'
        with:
          branch: release/v${{ steps.release-draft.outputs.tag_name }}
          title: "Release v${{ steps.release-draft.outputs.tag_name }}"
          body: |
            Release version ${{ steps.release-draft.outputs.tag_name }}

            ${{ steps.release-draft.outputs.body }}
          commit-message: "Bump version to v${{ steps.release-draft.outputs.tag_name }}"
          delete-branch: true
          token: ${{ secrets.RELEASE_TOKEN }} # Token to trigger workflows
